<?php
/**
 * UserNaturalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MarketPay API
 *
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserNaturalTest Class Doc Comment
 *
 * @category    Class */
// * @description UserNatural
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserNaturalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UserNatural"
     */
    public function testUserNatural()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {

    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {

    }

    /**
     * Test attribute "country_of_residence"
     */
    public function testPropertyCountryOfResidence()
    {

    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {

    }

    /**
     * Test attribute "income_range"
     */
    public function testPropertyIncomeRange()
    {

    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {

    }

}
