<?php
/**
 * V201ShipmentSeurshipmentsSenderTelephoneTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MarketPay API
 *
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V201ShipmentSeurshipmentsSenderTelephoneTest Class Doc Comment
 *
 * @category    Class */
// * @description V201ShipmentSeurshipmentsSenderTelephone
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V201ShipmentSeurshipmentsSenderTelephoneTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V201ShipmentSeurshipmentsSenderTelephone"
     */
    public function testV201ShipmentSeurshipmentsSenderTelephone()
    {

    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {

    }

}
