<?php
/**
 * KycApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MarketPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MarketPay API
 *
 * API for Smart Contracts and Payments
 *
 * OpenAPI spec version: v2.01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MarketPay;

use \MarketPay\Configuration;
use \MarketPay\ApiException;
use \MarketPay\ObjectSerializer;

/**
 * KycApiTest Class Doc Comment
 *
 * @category Class
 * @package  MarketPay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KycApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for kycDeleteLegalBoardMember
     *
     * .
     *
     */
    public function testKycDeleteLegalBoardMember()
    {
    }

    /**
     * Test case for kycDeleteLegalShareHolderNatural
     *
     * .
     *
     */
    public function testKycDeleteLegalShareHolderNatural()
    {
    }

    /**
     * Test case for kycGetFile
     *
     * .
     *
     */
    public function testKycGetFile()
    {
    }

    /**
     * Test case for kycGetLegal
     *
     * .
     *
     */
    public function testKycGetLegal()
    {
    }

    /**
     * Test case for kycGetLegalBoardMember
     *
     * .
     *
     */
    public function testKycGetLegalBoardMember()
    {
    }

    /**
     * Test case for kycGetLegalBoardMembers
     *
     * .
     *
     */
    public function testKycGetLegalBoardMembers()
    {
    }

    /**
     * Test case for kycGetLegalList
     *
     * .
     *
     */
    public function testKycGetLegalList()
    {
    }

    /**
     * Test case for kycGetLegalShareHolderNatural
     *
     * .
     *
     */
    public function testKycGetLegalShareHolderNatural()
    {
    }

    /**
     * Test case for kycGetLegalShareHolders
     *
     * .
     *
     */
    public function testKycGetLegalShareHolders()
    {
    }

    /**
     * Test case for kycGetNaturaList
     *
     * .
     *
     */
    public function testKycGetNaturaList()
    {
    }

    /**
     * Test case for kycGetNatural
     *
     * .
     *
     */
    public function testKycGetNatural()
    {
    }

    /**
     * Test case for kycGetValidation
     *
     * .
     *
     */
    public function testKycGetValidation()
    {
    }

    /**
     * Test case for kycGetValidationLegal
     *
     * .
     *
     */
    public function testKycGetValidationLegal()
    {
    }

    /**
     * Test case for kycPostDocument
     *
     * .
     *
     */
    public function testKycPostDocument()
    {
    }

    /**
     * Test case for kycPostDocumentBoardMember
     *
     * .
     *
     */
    public function testKycPostDocumentBoardMember()
    {
    }

    /**
     * Test case for kycPostDocumentShareholder
     *
     * .
     *
     */
    public function testKycPostDocumentShareholder()
    {
    }

    /**
     * Test case for kycPostLegal
     *
     * .
     *
     */
    public function testKycPostLegal()
    {
    }

    /**
     * Test case for kycPostLegalBoardMember
     *
     * .
     *
     */
    public function testKycPostLegalBoardMember()
    {
    }

    /**
     * Test case for kycPostLegalShareHolder
     *
     * .
     *
     */
    public function testKycPostLegalShareHolder()
    {
    }

    /**
     * Test case for kycPostNatural
     *
     * .
     *
     */
    public function testKycPostNatural()
    {
    }

    /**
     * Test case for kycPutDocument
     *
     * .
     *
     */
    public function testKycPutDocument()
    {
    }

    /**
     * Test case for kycPutDocumentBoardMember
     *
     * .
     *
     */
    public function testKycPutDocumentBoardMember()
    {
    }

    /**
     * Test case for kycPutDocumentShareholder
     *
     * .
     *
     */
    public function testKycPutDocumentShareholder()
    {
    }

    /**
     * Test case for kycPutLegal
     *
     * .
     *
     */
    public function testKycPutLegal()
    {
    }

    /**
     * Test case for kycPutLegalBoardMember
     *
     * .
     *
     */
    public function testKycPutLegalBoardMember()
    {
    }

    /**
     * Test case for kycPutLegalShareHolder
     *
     * .
     *
     */
    public function testKycPutLegalShareHolder()
    {
    }

    /**
     * Test case for kycPutRequest
     *
     * .
     *
     */
    public function testKycPutRequest()
    {
    }

    /**
     * Test case for kycPutRequestLegal
     *
     * .
     *
     */
    public function testKycPutRequestLegal()
    {
    }
}
